version: '3.8'
services:
  dev-db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PJBsSHgv
      POSTGRES_DB: nest
    networks:
      - localhost
  test-db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PJBsSHgv
      POSTGRES_DB: nest
    networks:
      - localhost
networks:
  localhost: